# Generated by Django 4.1.7 on 2023-03-31 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escritorio_advocacia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='atualizacao',
            field=models.TextField(blank=True, default=''),
        ),
    ]
