# Generated by Django 4.1.7 on 2023-03-31 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escritorio_advocacia', '0003_alter_processo_parte'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='advogadoResponsavel',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='responsavel', to='escritorio_advocacia.advogado'),
            preserve_default=False,
        ),
    ]
