# Generated by Django 4.1.7 on 2023-03-31 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escritorio_advocacia', '0004_processo_advogadoresponsavel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processo',
            old_name='numeroProcesso',
            new_name='numero',
        ),
        migrations.RenameField(
            model_name='processo',
            old_name='advogadoResponsavel',
            new_name='responsavel',
        ),
    ]
