# Generated by Django 4.1.7 on 2023-03-31 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escritorio_advocacia', '0005_rename_numeroprocesso_processo_numero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='numero',
            field=models.DecimalField(decimal_places=0, max_digits=20),
        ),
    ]
