# Generated by Django 4.1.7 on 2023-03-31 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escritorio_advocacia', '0006_alter_processo_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advogado',
            name='telefone',
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
    ]
