# Generated by Django 4.1.7 on 2023-03-31 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escritorio_advocacia', '0007_alter_advogado_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='parte',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='processo',
            name='responsavel',
            field=models.CharField(max_length=100),
        ),
    ]
