# Generated by Django 4.1.7 on 2023-03-31 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escritorio_advocacia', '0010_remove_processo_partes_alter_processo_parte_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='parte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escritorio_advocacia.cliente'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escritorio_advocacia.advogado'),
        ),
    ]
