# Generated by Django 4.1.7 on 2023-04-01 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escritorio_advocacia', '0020_rename_atualizacao_processo_informacoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='criacao',
            field=models.DateTimeField(auto_created=True, verbose_name='Criação'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='informacoes',
            field=models.TextField(blank=True, default='', verbose_name='Informações'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='numero',
            field=models.DecimalField(decimal_places=0, max_digits=20, verbose_name='Número Processo'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsavel', to='escritorio_advocacia.advogado', verbose_name='Responsável'),
        ),
    ]
