# Generated by Django 4.1.7 on 2023-03-31 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escritorio_advocacia', '0008_alter_processo_parte_alter_processo_responsavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='partes',
            field=models.ManyToManyField(to='escritorio_advocacia.cliente'),
        ),
    ]
