# Generated by Django 4.1.7 on 2023-03-31 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escritorio_advocacia', '0009_processo_partes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processo',
            name='partes',
        ),
        migrations.AlterField(
            model_name='processo',
            name='parte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parte', to='escritorio_advocacia.cliente'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsavel', to='escritorio_advocacia.advogado'),
        ),
    ]
