# Generated by Django 4.1.7 on 2023-04-01 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escritorio_advocacia', '0013_alter_processo_parte_alter_processo_responsavel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processo',
            name='parte',
        ),
    ]
