# Generated by Django 4.1.7 on 2023-04-01 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escritorio_advocacia', '0016_remove_processo_parte'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='parte',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='parte', to='escritorio_advocacia.cliente'),
            preserve_default=False,
        ),
    ]
