# Generated by Django 4.1.7 on 2023-04-01 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escritorio_advocacia', '0018_alter_processo_parte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='parte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parte', to='escritorio_advocacia.cliente'),
        ),
    ]
