# Generated by Django 4.1.7 on 2023-04-01 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escritorio_advocacia', '0019_alter_processo_parte'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processo',
            old_name='atualizacao',
            new_name='informacoes',
        ),
    ]
