# Generated by Django 4.1.7 on 2023-04-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escritorio_advocacia', '0021_alter_processo_criacao_alter_processo_informacoes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='criacao',
            field=models.DateField(auto_created=True, verbose_name='Criação'),
        ),
    ]
