# Generated by Django 4.1.7 on 2023-04-01 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escritorio_advocacia', '0024_alter_processo_responsavel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
    ]
